2022-07-04_16-38-45 [http-nio-8083-exec-10] ERROR c.m.m.e.GlobalExceptionHandler - [500] during [POST] to [http://localhost:8084/auth/authorize] [AuthorizationClient#authorizeTheRequest(String)]: [{"timestamp":"2022-07-04T11:10:35.612+00:00","status":500,"error":"Internal Server Error","trace":"io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT vali... (6653 bytes)]
2022-07-04_16-38-45 [http-nio-8083-exec-1] ERROR c.m.m.e.GlobalExceptionHandler - [500] during [POST] to [http://localhost:8084/auth/authorize] [AuthorizationClient#authorizeTheRequest(String)]: [{"timestamp":"2022-07-04T11:11:01.071+00:00","status":500,"error":"Internal Server Error","trace":"io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT vali... (6653 bytes)]
2022-07-04_16-38-45 [http-nio-8083-exec-4] ERROR c.m.m.e.GlobalExceptionHandler - [500] during [POST] to [http://localhost:8084/auth/authorize] [AuthorizationClient#authorizeTheRequest(String)]: [{"timestamp":"2022-07-04T11:11:16.874+00:00","status":500,"error":"Internal Server Error","trace":"io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT vali... (6653 bytes)]
2022-07-04_16-38-45 [http-nio-8083-exec-7] ERROR c.m.m.e.GlobalExceptionHandler - [400] during [GET] to [http://localhost:8081/customer/getCustomerDetails/1] [CustomerServiceClient#getCustomerDetails(int,String)]: [{"timeStamp":"04-07-2022 04:41:35","message":"[500] during [POST] to [http://localhost:8084/auth/authorize] [AuthorizationClient#authorizeTheRequest(String)]: [{\"timestamp\":\"2022-07-04T11:11:35.320+00:00\",\"status\":500,\"error\":\"Internal Server Error\",\"trace\":\"io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT vali... (6653 bytes)]"}]
2022-07-04_16-38-45 [http-nio-8083-exec-1] ERROR c.m.m.e.GlobalExceptionHandler - [500] during [POST] to [http://localhost:8084/auth/authorize] [AuthorizationClient#authorizeTheRequest(String)]: [{"timestamp":"2022-07-04T11:11:56.374+00:00","status":500,"error":"Internal Server Error","trace":"io.jsonwebtoken.SignatureException: JWT signature does not match locally computed signature. JWT vali... (6653 bytes)]
2022-07-04_16-38-45 [HikariPool-1 connection adder] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Error thrown while acquiring connection from data source
org.h2.jdbc.JdbcSQLNonTransientConnectionException: The database is open in exclusive mode; can not open additional connections [90135-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.engine.SessionLocal.checkSuspended(SessionLocal.java:1240)
	at org.h2.engine.SessionLocal.isOpen(SessionLocal.java:1173)
	at org.h2.engine.SessionLocal.waitIfExclusiveModeEnabled(SessionLocal.java:1486)
	at org.h2.command.Command.executeQuery(Command.java:180)
	at org.h2.jdbc.JdbcConnection.isReadOnly(JdbcConnection.java:538)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:408)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
