2022-07-03_10-03-41 [http-nio-8084-exec-3] ERROR c.m.a.e.GlobalExceptionHandler - User with user name srisai already exists
2022-07-03_10-03-41 [http-nio-8084-exec-2] ERROR c.m.a.e.GlobalExceptionHandler - User with user name harsh already exists
2022-07-03_12-11-33 [http-nio-8084-exec-6] ERROR c.m.a.e.GlobalExceptionHandler - JSON parse error: Cannot construct instance of `cts.mfpe.authorization.entities.JwtRequest` (although at least one Creator exists): no boolean/Boolean-argument constructor/factory method to deserialize from boolean value (true); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `cts.mfpe.authorization.entities.JwtRequest` (although at least one Creator exists): no boolean/Boolean-argument constructor/factory method to deserialize from boolean value (true)
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 1]
2022-07-03_12-11-33 [http-nio-8084-exec-8] ERROR c.m.a.e.GlobalExceptionHandler - JSON parse error: Cannot construct instance of `cts.mfpe.authorization.entities.JwtRequest` (although at least one Creator exists): no boolean/Boolean-argument constructor/factory method to deserialize from boolean value (true); nested exception is com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot construct instance of `cts.mfpe.authorization.entities.JwtRequest` (although at least one Creator exists): no boolean/Boolean-argument constructor/factory method to deserialize from boolean value (true)
 at [Source: (org.springframework.util.StreamUtils$NonClosingInputStream); line: 1, column: 1]
2022-07-03_12-11-33 [http-nio-8084-exec-2] ERROR c.m.a.e.GlobalExceptionHandler - User with user name srisai already exists
2022-07-03_12-11-33 [HikariPool-1 connection adder] ERROR com.zaxxer.hikari.pool.HikariPool - HikariPool-1 - Error thrown while acquiring connection from data source
org.h2.jdbc.JdbcSQLNonTransientConnectionException: The database is open in exclusive mode; can not open additional connections [90135-214]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:678)
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:477)
	at org.h2.message.DbException.get(DbException.java:223)
	at org.h2.message.DbException.get(DbException.java:199)
	at org.h2.message.DbException.get(DbException.java:188)
	at org.h2.engine.SessionLocal.checkSuspended(SessionLocal.java:1240)
	at org.h2.engine.SessionLocal.transitionToState(SessionLocal.java:1232)
	at org.h2.engine.SessionLocal.waitIfExclusiveModeEnabled(SessionLocal.java:1480)
	at org.h2.command.Command.executeQuery(Command.java:180)
	at org.h2.jdbc.JdbcConnection.isReadOnly(JdbcConnection.java:538)
	at com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:408)
	at com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:369)
	at com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:476)
	at com.zaxxer.hikari.pool.HikariPool.access$100(HikariPool.java:71)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:726)
	at com.zaxxer.hikari.pool.HikariPool$PoolEntryCreator.call(HikariPool.java:712)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
2022-07-03_13-24-45 [http-nio-8084-exec-8] ERROR c.m.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2022-07-03_13-24-45 [http-nio-8084-exec-6] ERROR c.m.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2022-07-03_13-24-45 [http-nio-8084-exec-4] ERROR c.m.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2022-07-03_13-24-45 [http-nio-8084-exec-10] ERROR c.m.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2022-07-03_13-24-45 [http-nio-8084-exec-2] ERROR c.m.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2022-07-03_13-24-45 [http-nio-8084-exec-1] ERROR c.m.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2022-07-03_13-24-45 [http-nio-8084-exec-5] ERROR c.m.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2022-07-03_13-24-45 [http-nio-8084-exec-6] ERROR c.m.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2022-07-03_13-24-45 [http-nio-8084-exec-7] ERROR c.m.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2022-07-03_13-24-45 [http-nio-8084-exec-3] ERROR c.m.a.e.GlobalExceptionHandler - INVALID_CREDENTIALS
2022-07-03_15-33-32 [http-nio-8084-exec-6] ERROR c.m.a.e.GlobalExceptionHandler - User with user name aditya already exists
2022-07-03_15-33-32 [http-nio-8084-exec-5] ERROR c.m.a.e.GlobalExceptionHandler - User with user name aditya already exists
